language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source
  - chmod -R 777 app/storage
  - chmod -R 777 app/storage
  - mysql -e 'create database toguru'
  - php artisan migrate --seed

script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v

notifications:
  emails:
      - wisdom1027@gmail.com
