language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install
  - chmode -R 777 storage

script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs
  - phpunit

after_script:
  - php vendor/bin/co
